# Generated by Django 4.2.5 on 2023-09-16 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URLImagen', models.ImageField(null=True, upload_to='productos')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'db_table': 'ImagenesProductos',
            },
        ),
        migrations.CreateModel(
            name='IProducto',
            fields=[
                ('IDIProducto', models.AutoField(primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=20)),
                ('Color', models.CharField(max_length=15)),
                ('Genero', models.CharField(max_length=20)),
                ('Material', models.CharField(max_length=30)),
                ('Tipo', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PuntosC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Destino', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'iproductos',
            },
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='IDIProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.iproducto'),
        ),
    ]
