# Generated by Django 4.2.5 on 2023-10-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_imagenproducto_iproducto_delete_cuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseApartado',
            fields=[
                ('IDApartado', models.AutoField(primary_key=True, serialize=False)),
                ('FHDeApartado', models.DateTimeField()),
                ('ProductosT', models.IntegerField()),
                ('CantidadT', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCliente',
            fields=[
                ('IDCliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('ApellidoM', models.CharField(max_length=30)),
                ('ApellidoP', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Contrasena', models.CharField(max_length=30)),
                ('Monedero', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='BaseDonacion',
            fields=[
                ('IDDonacion', models.AutoField(primary_key=True, serialize=False)),
                ('FechaDeDonacion', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='IProducto',
            new_name='BaseIDProducto',
        ),
        migrations.CreateModel(
            name='BaseCDonante',
            fields=[
                ('IDDonante', models.AutoField(primary_key=True, serialize=False)),
                ('PuntosAgregados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IDCliente1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.basecliente')),
                ('IDDonacion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.basedonacion')),
            ],
        ),
        migrations.CreateModel(
            name='BaseCanjeo',
            fields=[
                ('IDCanjeo', models.AutoField(primary_key=True, serialize=False)),
                ('FHCanjeo', models.DateTimeField()),
                ('IDCliente3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.basecliente')),
                ('IDIProducto2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.baseidproducto')),
            ],
        ),
        migrations.CreateModel(
            name='BaseAProducto',
            fields=[
                ('IDAProducto', models.AutoField(primary_key=True, serialize=False)),
                ('IDApartado1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.baseapartado')),
                ('IDCliente2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.basecliente')),
                ('IDIProducto1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.baseidproducto')),
            ],
        ),
    ]
